{% set name = "minijinja" %}
{% set version = "1.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/minijinja-{{ version }}.tar.gz
  sha256: f423e2da0a139a82024c1c62f17a900ddde3c1559f339265a2ac3ed525ef22e5

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<38]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - crossenv                            # [build_platform != target_platform]
    - maturin >=0.15,<0.16                # [build_platform != target_platform]
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=0.15,<0.16
    - pip
  run:
    - python
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  imports:
    - minijinja
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mitsuhiko/minijinja
  summary: An experimental Python binding of the Rust MiniJinja template engine.
  license: Apache-2.0
  license_file:
    - LICENSE
    - local_dependencies/minijinja/LICENSE
    - THIRDPARTY.yml
  dev_url: https://github.com/mitsuhiko/minijinja

extra:
  recipe-maintainers:
    - synapticarbors
