{% set name = "minijinja" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/minijinja-{{ version }}.tar.gz
  sha256: 4411052c7a60f8d56468cc6d17d45d72be3d5e89e9578a04f8336cc56601523c

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<38]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - crossenv                            # [build_platform != target_platform]
    - maturin >=0.15,<0.16                # [build_platform != target_platform]
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=0.15,<0.16
    - pip
  run:
    - python

test:
  imports:
    - minijinja
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mitsuhiko/minijinja
  summary: An experimental Python binding of the Rust MiniJinja template engine.
  license: Apache-2.0
  license_file:
    - LICENSE
    - local_dependencies/minijinja/LICENSE
    - THIRDPARTY.yml
  dev_url: https://github.com/mitsuhiko/minijinja

extra:
  recipe-maintainers:
    - synapticarbors
