{% set name = "minijinja" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/minijinja-{{ version }}.tar.gz
  sha256: 752f44e75e18e0cf03751bdbead031f88cefdebd7d5140b9c1e6a6d2de3cc1cc

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [py<38]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - crossenv                            # [build_platform != target_platform]
    - maturin >=1.5                       # [build_platform != target_platform]
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.5
    - pip
  run:
    - python

test:
  imports:
    - minijinja
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mitsuhiko/minijinja
  summary: An experimental Python binding of the Rust MiniJinja template engine.
  license: Apache-2.0
  license_file:
    - LICENSE
    - minijinja/LICENSE
    - THIRDPARTY.yml
  dev_url: https://github.com/mitsuhiko/minijinja

extra:
  recipe-maintainers:
    - synapticarbors
