# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.14.0"
  maturin_min: "1.5"
  python_check_min: "3.10"

package:
  name: minijinja
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/m/minijinja/minijinja-${{ version }}.tar.gz
  sha256: 6475823718bf1bce09eb190dd93aa5cd1412cec2c4b1736efa7125842300f0ae

build:
  number: 1
  skip: is_abi3 and not is_python_min
  script:
    - cargo-bundle-licenses --format=yaml --output=THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps --disable-pip-version-check
    - echo "" > ${{ SP_DIR }}/minijinja/py.typed
  python:
    version_independent: true

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - crossenv
        - maturin >=${{ maturin_min }}
        - python
  host:
    - maturin >=${{ maturin_min }}
    - pip
    - python
    - if: is_abi3
      then: python-abi3
  run:
    - python

tests:
  - python:
      imports: minijinja
      pip_check: true
      python_version:
        - if: is_abi3
          then: ${{ python_min }}.*
        - "*"
  - files:
      source:
        - minijinja-py/tests/
    requirements:
      run:
        - mypy
        - pytest-cov
        - python ${{ python_check_min }}.*
    script:
      - cd minijinja-py
      - coverage run --source minijinja --branch -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=84
      - mypy -p minijinja

about:
  summary: An experimental Python binding of the Rust MiniJinja template engine.
  license: Apache-2.0
  license_file:
    - LICENSE
    - minijinja/LICENSE
    - THIRDPARTY.yml
  homepage: https://pypi.org/project/minijinja
  repository: https://github.com/mitsuhiko/minijinja

extra:
  recipe-maintainers:
    - synapticarbors
    - bollwyvl
