# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.16.0"
  maturin_min: "1.5"
  python_check_max: "3.14"

package:
  name: minijinja
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/m/minijinja/minijinja-${{ version }}.tar.gz
  sha256: 6109593eeb36e3139d4a7a923e3e45d73143f1bf5838d39731eb883310a2a900

build:
  number: 0
  skip: is_abi3 and not is_python_min
  script:
    env:
      # for windows
      # ⚠ warning Error reading output: Custom { kind: InvalidData, error: "stream did not contain valid UTF-8" }
      PYTHONIOENCODING: utf-8
    content:
      - cargo-bundle-licenses --format=yaml --output=THIRDPARTY.yml
      - ${{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps --disable-pip-version-check
      # see: https://github.com/mitsuhiko/minijinja/pull/853
      # SP_DIR is broken on 3.14t, use python API
      - ${{ PYTHON }} -c "import site, pathlib; (pathlib.Path(site.getsitepackages()[-1]) / 'minijinja/py.typed').touch()"
  python:
    version_independent: ${{ is_abi3 }}

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - crossenv
        - maturin >=${{ maturin_min }}
        - python
  host:
    - maturin >=${{ maturin_min }}
    - pip
    - python
    - if: is_abi3
      then: python-abi3
  run:
    - python

tests:
  - if: is_abi3
    then:
      python:
        imports: minijinja
        pip_check: true
        python_version:
          - ${{ python_min }}.*
          - ${{ python_check_max }}.*
    else:
      python:
        imports: minijinja
        pip_check: true
  - files:
      source:
        - minijinja-py/tests/
    requirements:
      run:
        - mypy
        - pytest-cov
        - python ${{ python_min ~ ".*" if is_abi3 }}
    script:
      - cd minijinja-py
      - coverage run --source minijinja --branch -m pytest -vv --tb=long --color=yes
      - coverage report --show-missing --skip-covered --fail-under=84
      - mypy -p minijinja

about:
  summary: An experimental Python binding of the Rust MiniJinja template engine.
  license: Apache-2.0
  license_file:
    - LICENSE
    - minijinja/LICENSE
    - THIRDPARTY.yml
  homepage: https://pypi.org/project/minijinja
  repository: https://github.com/mitsuhiko/minijinja

extra:
  recipe-maintainers:
    - synapticarbors
    - bollwyvl
